ta404:
  application:
    name: mids
    version: 5.4.1-RELEASE
spring:
  profiles:
    active: dev,datasource,websecurity,cache
  application:
    name: ${ta404.application.name}
  main:
    allow-bean-definition-overriding: true
  banner:
    location: banner.txt
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 20MB
server:
  port: ${system.server-port:39625}
  servlet:
    session:
      timeout: 14400s
    context-path: /mids

