ta404:
  inter-error-msg: 出现了点小意外,请稍后再试或联系管理员!  # 框架对服务器内部异常和未知错误的统一信息处理
  limit:
    enable: ${system.limit-enable:true}
    repeat-expire-time: 200
    repeat-extra-url:
      - /codetable/getCode
    rates:
      - url: /indexRestService/defaultOpen
        rate: 1.0
      - url: /indexRestService/rate1
        rate: 2.0
      - url: /indexRestService/rate2
        max-count: 2
        timeout: 2000
  log:
    output-type: console,file
    package-level:
      com.yinhai.ta404.module.mybatis.mapper.Ta404SupportMapper.executeForTimestamp: ERROR
      com.yinhai.ta404.module.encryption.interceptor.DecryptionMybatisInterceptor: ERROR
      com.yinhai.ta404.module.encryption.interceptor.EncryptionMybatisInterceptor: ERROR
      com.yinhai.mids.business.mapper.TaskLockMapper: ERROR
      com.yinhai.mids.business.mapper.KeyaApplyTaskMapper.queryTodoTasks_COUNT: ERROR
      com.yinhai.mids.business.mapper.KeyaApplyTaskMapper.queryTodoTasks: ERROR
      com.yinhai.mids.business.mapper.KeyaQueryTaskMapper.queryTodoTasks_COUNT: ERROR
      com.yinhai.mids.business.mapper.KeyaQueryTaskMapper.queryTodoTasks: ERROR
      com.yinhai.mids.business.mapper.MprTaskMapper.queryTodoTasks_COUNT: ERROR
      com.yinhai.mids.business.mapper.MprTaskMapper.queryTodoTasks: ERROR
      com.yinhai.mids.business.mapper.SpineRecogTaskMapper.queryTodoTasks_COUNT: ERROR
      com.yinhai.mids.business.mapper.SpineRecogTaskMapper.queryTodoTasks: ERROR
      com.yinhai: DEBUG
      org.springframework.boot: INFO
    appender-type:
      file:
        file-name-pattern: /u01/mids/backend/logs/file_%d{yyyy-MM-dd}_%i.log  # 文件地址
        max-history: 30    # 文件最大保留天数
        max-file-size: 1024MB    # 单个文件最大容量(单位可以是kb,mb,gb)
        clear-size: 12GB    # 所有文件最大容量(单位可以是kb,mb,gb
  modules:
    captcha:
      number-check-code-level: 5
      user-check-code: false
      # 验证码存储方式 可选 inMemory/redis
      cache-type: inMemory
      # 验证码方式 可选 simple/clickWord/blockPuzzle
      captcha-type: "simple"
      password-validation-error-number: ${system.password-validation-error-number:0}
      cacheNumber: 10000
      timingClear: 180
  component:
    org:
      multiple-org: 1
      multiple-role: true
    security:
      db-encoder-type: BCrypt-Sm3
      maximum-sessions: -1
      # 发布时 需要配置密码错误锁定策略
      password-policy-list:
        # 可以实现自动进行按大小排序,但是errorNum不能设置为一样的,可以无限扩展加,只要符合数据,且锁定时间应该跟随次数上升进行递增才对
        # 如果输错6次,就会将账号锁定2分钟才会进行解锁
        - errorNum: 6
          lockTime: 2
        # 2分钟内如果输错4次,就会锁定账号一分钟
        - errorNum: 4
          lockTime: 1 #锁定一分钟
          timeInterval: 2
        - errorNum: 8
          lockTime: -1
      # 是否加密用户名,开启会在登录或登录页修改密码时对用户名加密, 默认false
      encrypt-login-id: true
      # 密码等级,从1到4,默认等级为3
      # 4种字符类型：0-9，a-z，A-Z，特殊字符
      # 难度等级1:6位纯数字
      # 难度等级2:4选2，8-20位
      # 难度等级3:4选3，8-20位
      # 难度等级4:4选4，8-20位
      password-level: 3
      permit-urls:
        - /oss/*
        - /doc.html
        - /webjars/**
        - /v3/**
        - /swagger-ui/**
        - /**
      login-permit-urls:
    examine:
      examine-switch: true






