ta404:
  application:
    name: mids
    version: 1.0.0
spring:
  profiles:
    active: dev,datasource,websecurity,cache,system,token
  application:
    name: ${ta404.application.name}
  main:
    allow-bean-definition-overriding: true
  banner:
    location: banner.txt
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
server:
  port: ${system.server-port:39625}
  servlet:
    session:
      timeout: 14400s
    context-path: /mids-api
knife4j:
  enable: true
  production: false
  setting:
    enable-open-api: true
