ta404:
  modules:
    cache:
      # SpringCache注解默认支持的缓存(后续需要启用primary对应的缓存配置eg: ehcache.active=true)
      primary: redis
      redis:
        # 是否启动redis(默认不启用)
        active: true
        # redis缓存模式single、cluster
        type: single
        # SpringCache注解缓存失效时间(秒)，0为不失效
        expire: 1800
        #单个缓存自定义参数
        define:
          taStatisticAnalysisCache:
            expire: 600
          taPermissionCache:
            expire: 600
        # 单点模式
        single:
          host-name: ${redis.host-name}
          port: ${redis.port}
          # 口令(可选)
          password: ${redis.password}
          # 指定redis数据库（仅单节点可用，默认为0，集群模式不支持指定数据库）
          db-index: ${redis.database}
        lettuce:
          io:
            # (可选)io操作线程数，空默认为cpu的availableProcessors，决定lettuce-eventExecutorLoop大小，最小值2
            ioThreadPoolSize:
            # (可选)决定lettuce-nioEventLoop大小，空默认为cpu的availableProcessors，最小值2
            computationThreadPoolSize:
          pool:
            # 连接池的最大数据库连接数，默认 8
            maxTotal: 100
            # 最大空闲连接数，默认 8
            maxIdle: 20
            # 最小空闲连接数，默认 0
            minIdle: 10
            # 连接耗尽时是否阻塞, false报异常,ture阻塞直到超时, 默认true
            blockWhenExhausted: true
            # 最大建立连接等待时间
            maxWaitMillis: 3000
            # 是否在从池中取出连接实例前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
            testOnBorrow: false
            # 是否在return连接实例给pool前进行检验
            testOnReturn: false
            # 在空闲时检查有效性, 校验失败会从pool中drop掉 默认false（这一项只有在timeBetweenEvictionRunsMillis大于0时才有意义）
            testWhileIdle: true
            # 逐出连接的最小空闲时间 默认1800000毫秒(30分钟) ；（这一项只有在timeBetweenEvictionRunsMillis大于0时才有意义）
            minEvictableIdleTimeMillis: 60000
            # 逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
            timeBetweenEvictionRunsMillis: 30000
            # 每次逐出检查时 逐出的最大数目 如果为负数就是 : 1/abs(n), 默认3
            numTestsPerEvictionRun: -1

